Repository ballerina-platform/ballerina-dev-website, pull requests merged in 2019-12, with the labels that each got.

#126 Change the description of the language specification box
  learn.md
Labels: Type/Docs

#73 Remove the CLI Commands Section from the Learn Page
  learn.md
  learn/cli-commands.md
Labels: Points/0.5, Type/Docs

#131 Improve the Content of the Community Page
  community.md
Labels: Type/Docs

#147 Add the Sub Sections Under the "Using the Plugin" Section
  learn/intellij-plugin-doc.md
  learn/tools-ides/intellij-plugin.md
  learn/tools-ides/intellij-plugin/using-intellij-plugin-features.md
  learn/tools-ides/intellij-plugin/using-the-intellij-plugin.md
  learn/tools-ides/vscode-plugin.md
  learn/tools-ides/vscode-plugin/graphical-editor.md
  learn/tools-ides/vscode-plugin/run-all-tests.md
Labels: Type/Docs

#150 Add lunr search implementation to the site
  js/ballerina-common.js
  js/lunr.js
  js/searchIndex.js
  js/site-search.js
  search.html
Labels: enhancement

#155 Improve index to have ballerina module titles
  js/searchIndex.js
  js/site-search.js
Labels: Type/New Feature

#156 Improve the search index and usability
  js/ballerina-common.js
  js/searchIndex.js
  js/site-search.js
  search.html
Labels: Type/New Feature

#152 Update Code Snippets of the Service Skeleton Start/Stop Utility Example
  learn/how-to-test-ballerina-code.md
Labels: Type/Docs

#40 Fix formatting issues in how to extend b7a page
  learn/how-to-extend-ballerina.md
Labels: Priority/High

#170 Fix page mapping issue with bio v1.1
  v1-1/learn/api-docs/index.html
  v1-1/learn/ballerina-streaming-reference.md
  v1-1/learn/cli-commands.md
  v1-1/learn/events.md
  v1-1/learn/faq.md
  v1-1/learn/how-to-deploy-and-run-ballerina-programs.md
  v1-1/learn/how-to-document-ballerina-code.md
  v1-1/learn/how-to-extend-ballerina.md
  v1-1/learn/how-to-generate-code-for-protocol-buffers.md
  v1-1/learn/how-to-observe-ballerina-code.md
  v1-1/learn/how-to-publish-modules.md
  v1-1/learn/how-to-structure-ballerina-code.md
  v1-1/learn/how-to-test-ballerina-code.md
  v1-1/learn/how-to-use-openapi-tools.md
  v1-1/learn/how-to-write-secure-ballerina-code.md
  v1-1/learn/installing-ballerina.md
  v1-1/learn/quick-tour.md
  v1-1/learn/set-up-ballerina-sdk.md
  v1-1/learn/style-guide.md
  v1-1/learn/style-guide/definitions.md
  v1-1/learn/style-guide/expressions.md
  v1-1/learn/tools-ides.md
  v1-1/learn/tools-ides/intellij-plugin.md
  v1-1/learn/tools-ides/intellij-plugin/using-intellij-plugin-features.md
  v1-1/learn/tools-ides/intellij-plugin/using-the-intellij-plugin.md
  v1-1/learn/tools-ides/vscode-plugin.md
  v1-1/learn/tools-ides/vscode-plugin/documentation-viewer.md
  v1-1/learn/tools-ides/vscode-plugin/graphical-editor.md
  v1-1/learn/tools-ides/vscode-plugin/language-intelligence.md
  v1-1/learn/tools-ides/vscode-plugin/run-and-debug.md
Labels: bug
