Repository ballerina-platform/ballerina-dev-website, pull requests merged in 2020-03, with the labels that each got.

#261 Fix the V1.0 Links in the Style Guide
  v1-0/learn/api-docs/ballerina/transactions/annotations.html
  v1-0/learn/api-docs/ballerina/websub/functions.html
  v1-0/learn/api-docs/ballerina/websub/objects/Hub.html
  v1-0/learn/style-guide/definitions.md
  v1-0/learn/style-guide/expressions.md
Labels: Type/Docs

#268 Update the Terms of Service of the B.io
  terms-of-service.md
Labels: Type/Docs

#267 Update the Privacy Policy of the B.io
  privacy-policy.md
Labels: Type/Docs

#271 Fix the TOC Links in the Terms of Service
  terms-of-service.md
Labels: Type/Docs

#291 Remove `/learn` Redirections from V1-1 and Add Redirections to V1-2
  events.md
  index.html
  v1-1/learn.md
  v1-2/learn.md
  v1-2/learn/cli-commands.md
  v1-2/learn/installing-ballerina.md
  v1-2/learn/quick-tour.md
  v1-2/learn/set-up-ballerina-sdk.md
  v1-2/learn/style-guide.md
  v1-2/learn/tools-ides/intellij-plugin.md
  v1-2/learn/tools-ides/vscode-plugin.md
Labels: Type/Docs, documentation

#281 Update video link on events page
  events.md
Labels: Type/Docs

#279 Add Function mocking documentation
  v1-2/learn/how-to-test-ballerina-code.md
Labels: Type/Docs

#292 Update how to guide of protocol buffers
  v1-2/learn/how-to-generate-code-for-protocol-buffers.md
Labels: documentation

#296 Update deploy and run BBG for 1.2 release
  v1-2/learn/how-to-deploy-and-run-ballerina-programs.md
Labels: Type/Docs

#306 Add DevOps Pro talk
  events.md
  index.html
Labels: Type/Docs

#308 Fix the Broken Links Identified in the 1.2.0 RC Stage
  license-of-site.md
  v1-2/learn/how-to-keep-ballerina-up-to-date.md
  v1-2/learn/how-to-write-secure-ballerina-code.md
  v1-2/learn/installing-ballerina.md
  v1-2/learn/set-up-ballerina-sdk.md
  v1-2/learn/tools-ides/intellij-plugin.md
  v1-2/learn/tools-ides/intellij-plugin/using-intellij-plugin-features.md
  v1-2/learn/tools-ides/vscode-plugin.md
  v1-2/learn/tools-ides/vscode-plugin/graphical-editor.md
  v1-2/learn/tools-ides/vscode-plugin/language-intelligence.md
  v1-2/learn/tools-ides/vscode-plugin/run-all-tests.md
  v1-2/learn/tools-ides/vscode-plugin/run-and-debug.md
Labels: Type/Docs

#309 How-to guide on Java interoperbility
  v1-2/learn.md
  v1-2/learn/how-to-use-java-interoperability.md
Labels: documentation

#322 Update the Spec Version in Bio for the 1.2 Release
  spec.md
  spec/lang/2020R1/index.html
  spec/lang/2020R1/lib/array.bal
  spec/lang/2020R1/lib/boolean.bal
  spec/lang/2020R1/lib/decimal.bal
  spec/lang/2020R1/lib/error.bal
  spec/lang/2020R1/lib/float.bal
  spec/lang/2020R1/lib/future.bal
  spec/lang/2020R1/lib/int.bal
  spec/lang/2020R1/lib/map.bal
  spec/lang/2020R1/lib/object.bal
  spec/lang/2020R1/lib/stream.bal
  spec/lang/2020R1/lib/string.bal
  spec/lang/2020R1/lib/table.bal
  spec/lang/2020R1/lib/typedesc.bal
  spec/lang/2020R1/lib/value.bal
  spec/lang/2020R1/lib/versions.json
  spec/lang/2020R1/lib/xml.bal
  spec/lang/2020R1/style/ballerina-language-specification.css
  spec/lang/2020R1/style/ballerina-language-specification.js
Labels: Type/Docs

#327 Fix the Appendix C link in the Spec
  spec/lang/2020R1/index.html
Labels: Type/Docs

#328 Add All Required Redirections in MD Files of Learn Directory
  v1-2/learn.md
  v1-2/learn/ballerina-streaming-reference.md
  v1-2/learn/cli-commands.md
  v1-2/learn/faq.md
  v1-2/learn/how-to-deploy-and-run-ballerina-programs.md
  v1-2/learn/how-to-document-ballerina-code.md
  v1-2/learn/how-to-extend-ballerina.md
  v1-2/learn/how-to-generate-code-for-protocol-buffers.md
  v1-2/learn/how-to-keep-ballerina-up-to-date.md
  v1-2/learn/how-to-observe-ballerina-code.md
  v1-2/learn/how-to-publish-modules.md
  v1-2/learn/how-to-structure-ballerina-code.md
  v1-2/learn/how-to-test-ballerina-code.md
  v1-2/learn/how-to-use-java-interoperability.md
  v1-2/learn/how-to-use-openapi-tools.md
  v1-2/learn/how-to-write-secure-ballerina-code.md
  v1-2/learn/installing-ballerina.md
  v1-2/learn/quick-tour.md
  v1-2/learn/style-guide.md
  v1-2/learn/style-guide/annotations_documentation_and_comments.md
  v1-2/learn/style-guide/definitions.md
  v1-2/learn/style-guide/expressions.md
  v1-2/learn/style-guide/operators_keywords_and_types.md
  v1-2/learn/style-guide/statements.md
  v1-2/learn/tools-ides/intellij-plugin.md
  v1-2/learn/tools-ides/intellij-plugin/using-intellij-plugin-features.md
  v1-2/learn/tools-ides/intellij-plugin/using-the-intellij-plugin.md
  v1-2/learn/tools-ides/vscode-plugin.md
  v1-2/learn/tools-ides/vscode-plugin/documentation-viewer.md
  v1-2/learn/tools-ides/vscode-plugin/graphical-editor.md
  v1-2/learn/tools-ides/vscode-plugin/language-intelligence.md
  v1-2/learn/tools-ides/vscode-plugin/run-all-tests.md
  v1-2/learn/tools-ides/vscode-plugin/run-and-debug.md
Labels: Type/Docs

#323 Add the Diagram to the Interoperability How-To Guide
  v1-2/learn/how-to-use-java-interoperability.md
  v1-2/learn/images/interoperability-diagram.png
Labels: Type/Docs

#332 Fix the How To Guide Links in Docerina HTMLs
  v1-2/learn/api-docs/ballerina/observe/index.html
  v1-2/learn/api-docs/ballerina/websub/index.html
Labels: Type/Docs

#333 Update why pages
  img/why-pages/sequence-diagrams-for-programming-1.png
  img/why-pages/sequence-diagrams-for-programming-2.png
  img/why-pages/sequence-diagrams-for-programming-3.png
  img/why-pages/sequence-diagrams-for-programming-4.png
  img/why-pages/sequence-diagrams-for-programming-5.png
  img/why-pages/the-network-in-the-language-1.png
  index.html
  why/from-code-to-cloud.md
  why/sequence-diagrams-for-programming.md
  why/the-network-in-the-language.md
Labels: Type/Docs

#335 Remove the "Edit on GitHub" Option at the Top of Each BBE Page
  _layouts/ballerina-example-page.html
Labels: Type/Docs

#343 Add missing parts in test api doc
  v1-2/learn/api-docs/ballerina/test/annotations.html
  v1-2/learn/api-docs/ballerina/test/index.html
Labels: Type/Docs

#346 Update why pages
  why/from-code-to-cloud.md
  why/sequence-diagrams-for-programming.md
Labels: Type/Docs
