Repository ballerina-platform/ballerina-dev-website, pull requests merged in 2021-06, with the labels that each got.

#2293 Improve query user guide
  learn/user-guide/data-and-events-processing/using-language-integrated-queries.md
Labels: Type/Improvement

#2294 Fix the Hello World BBE
  _data/bbenavswanlake.yml
  learn/by-example/hello-world.html
Labels: SwanLakeDump, Type/Docs

#2303 Fix the Video Links
  community.md
  index.html
  learn/language-concepts/language-concepts.md
Labels: SwanLakeDump, Type/Docs

#2325 Fix the "Download" Top Menu Link
  _includes/nav.html
Labels: SwanLakeDump, Type/Docs

#2327 Fix BBE Links
  learn/by-example/hello-world.html
Labels: SwanLakeDump, Type/Docs

#2330 Fix the Underlining Issue on the "Learn" Page
  css/ballerina-io-learn-v2.css
Labels: Type/Docs

#2334 Fix the New Tab Opening of the Top Menu
  _includes/nav.html
Labels: SwanLakeDump, Type/Docs

#2324 Add the Swan lake Beta1 Release Note
  _data/releasenotes.yml
  download.html
  downloads/swan-lake-release-notes/swan-lake-alpha5/RELEASE_NOTE.md
  downloads/swan-lake-release-notes/swan-lake-beta1/RELEASE_NOTE.md
  learn/user-guide/why-ballerina/cloud-native.md
Labels: Type/Docs

#2346 Fix the Scroll Bar of the BBE Layout
  css/bbe-page.css
Labels: SwanLakeDump, Type/Docs

#2347 Add the v2021R1 Spec
  learn/user-guide/getting-started/setting-up-ballerina.md
  spec/lang/2021R1/index.html
  spec/lang/2021R1/style/ballerina-language-specification.css
  spec/lang/2021R1/style/ballerina-language-specification.js
Labels: SwanLakeDump, Type/Docs

#2348 Update the SLBeta1 Release Note
  css/ballerina-io-learn-v2.css
  download.html
  downloads/swan-lake-release-notes/swan-lake-beta1/RELEASE_NOTE.md
Labels: Type/Docs

#2350 Fix the Capitalisation Issues in Learn Pages
  _data/learnnavswanlake.yml
  learn/tooling-guide/cli-tools/update-tool.md
  learn/tooling-guide/visual-studio-code-extension/vs-code-commands.md
  learn/user-guide/ballerina-packages/creating-your-first-ballerina-package.md
  learn/user-guide/ballerina-packages/dependencies.md
  learn/user-guide/ballerina-packages/modules.md
  learn/user-guide/ballerina-packages/package-layout.md
  learn/user-guide/ballerina-packages/sharing-a-library-package.md
  learn/user-guide/deployment/code-to-cloud/code-to-cloud.md
  learn/user-guide/getting-started/setting-up-ballerina.md
  learn/user-guide/getting-started/writing-your-first-ballerina-program.md
  learn/user-guide/testing-ballerina-code/writing-tests.md
Labels: SwanLakeDump, Type/Docs

#2352 Fix Structural Issues in Learn Pages
  _data/learnnavswanlake.yml
  learn/user-guide/code-organization/coding-conventions.md
  learn/user-guide/code-organization/coding-conventions/README.md
  learn/user-guide/code-organization/coding-conventions/annotations_documentation_and_comments.md
  learn/user-guide/code-organization/coding-conventions/expressions.md
  learn/user-guide/code-organization/coding-conventions/operators_keywords_and_types.md
  learn/user-guide/code-organization/coding-conventions/statements.md
  learn/user-guide/code-organization/coding-conventions/top-level-definitions.md
  learn/user-guide/code-organization/documenting-ballerina-code.md
  learn/user-guide/interoperability/calling-java-code-from-ballerina.md
  learn/user-guide/observability/observing-ballerina-code.md
  learn/user-guide/publishing-packages-to-ballerina-central.md
  learn/user-guide/running-ballerina-code.md
  learn/user-guide/structuring-ballerina-code/structuring-ballerina-code.md
  learn/user-guide/structuring-ballerina-code/working-with-ballerina-modules.md
Labels: Type/Docs

#2363 Fix Formatting Issues in Ballerina Packages Pages
  learn/user-guide/ballerina-packages/creating-your-first-ballerina-package.md
  learn/user-guide/ballerina-packages/dependencies.md
  learn/user-guide/ballerina-packages/modules.md
  learn/user-guide/ballerina-packages/package-layout.md
  learn/user-guide/ballerina-packages/sharing-a-library-package.md
Labels: SwanLakeDump, Type/Docs

#2364 Fix More Formatting Issues in Learn Pages
  learn/user-guide/ballerina-packages/creating-your-first-ballerina-package.md
  learn/user-guide/interoperability/calling-java-code-from-ballerina.md
Labels: SwanLakeDump, Type/Docs

#2371 Fix Bio Issues and Regen BBEs
  download.html
  learn/by-example/hello-world.html
  learn/language-concepts/language-concepts.md
Labels: SwanLakeDump, Type/Docs

#2382 Add the BBE Introduction Page
  _data/bbenavswanlake.yml
  css/ballerina-io-bbe.css
  learn/bbe-introduction.md
  learn/by-example/counter-metrics.html
  learn/by-example/gauge-metrics.html
  learn/by-example/hello-world.html
  learn/by-example/inferring-isolated.html
  learn/by-example/isolated-functions.html
  learn/by-example/isolated-objects.html
  learn/by-example/isolated-variables.html
  learn/by-example/raw-templates.html
  learn/by-example/tracing.html
  learn/by-example/xml-data-model.html
Labels: SwanLakeDump, Type/Docs

#2391 Increase the Height of the Playground Widget
  css/home-page-2020.css
Labels: SwanLakeDump, Type/Docs

#2392 Add an Image Showing the Ballerina Version on VSCode
  learn/images/show-version-on-vscode.png
  learn/tooling-guide/visual-studio-code-extension/quick-start.md
Labels: SwanLakeDump, Type/Docs

#2395 Generate the BBE Left Nav from JSON
  _data/all-bbes.json
  _data/bbenavswanlake.yml
  _includes/bbe-nav-swanlake.html
  js/philosophy.js
  learn/by-example/all-bbes.json
  learn/user-guide/why-ballerina/cloud-native.md
  learn/user-guide/why-ballerina/data-oriented.md
  learn/user-guide/why-ballerina/flexibly-typed.md
  why-ballerina/batteries-included.md
  why-ballerina/from-code-to-cloud.md
  why-ballerina/network-aware-type-system.md
  why-ballerina/sequence-diagrams-for-programming.md
  why-ballerina/the-network-in-the-language.md
Labels: SwanLakeDump

#2403 Fix Broken Links After the Swan Lake Beta Release
  community/newsletter/2020-1.md
  community/newsletter/2020-2.md
  community/newsletter/2020-5.md
  community/newsletter/2021-1.md
  downloads/swan-lake-release-notes/swan-lake-preview7/RELEASE_NOTE.md
  learn/user-guide/network-communication/HTTP/http-clients/communication-resiliency.md
  learn/user-guide/network-communication/HTTP/http-clients/data-streaming.md
  learn/user-guide/network-communication/WebSocket/securing-websocket-communication.md
  swan-lake/learn/tools-ides/setting-up-intellij-idea/using-intellij-plugin-features.md
Labels: Area/Docs, SwanLakeDump

#2407 Revert the BBE YAML and HTML Files
  _data/bbenavswanlake.yml
  _includes/bbe-nav-swanlake.html
Labels: Area/Docs, SwanLakeDump

#2408 Add the Ballerina Shell Learn Page
  _data/toolingguidenavswanlake.yml
  learn/tooling-guide/ballerina-shell.md
Labels: Area/Docs, SwanLakeDump

#2434 Add the Redirections of the "Language Concepts" Page
  learn/language-concepts/language-concepts.md
Labels: Area/Docs

#2441 Improve the "Building From Source" Page Content
  learn/user-guide/getting-started/building-from-source.md
Labels: Area/Docs

#2475 Add the "Paste JSON as Record" VS Code Command to Docs
  documentation.md
  learn/images/paste-json-as-record.gif
  learn/tooling-guide/visual-studio-code-extension/vs-code-commands.md
Labels: Area/Docs

#2479 Upload Images for the Dev Site Wiki
  img/bbe-on-demand-workflow.png
  img/obtain-artifact-id.png
Labels: Area/Docs

#2486 Update the BBE Styles for the Div Structure
  css/bbe-page.css
Labels: Area/Docs

#2507 Regenerate the 1.2 Deployment BBEs with the Div Structure
  1.2/learn/.DS_Store
  1.2/learn/by-example/aws-lambda-deployment.html
  1.2/learn/by-example/azure-functions-deployment.html
  1.2/learn/by-example/docker-deployment.html
  1.2/learn/by-example/knative-deployment.html
  1.2/learn/by-example/kubernetes-deployment.html
  1.2/learn/by-example/openshift-deployment.html
Labels: Area/Docs

#2490 Remove Google Group References from Docs
  404.html
  community.md
  downloads/stable-release-notes/1.0.0/RELEASE_NOTE.html
  page-not-available.html
Labels: Area/Docs

#2515 Add the New Reference By Examples Structure
  _data/all-bbes.json
  index.html
  learn-beta2-column.md
  learn-beta2.md
  learn/bbe-introduction.md
  learn/by-example/all-bbes.json
  learn/by-example/index.html
Labels: Area/Docs

#2521 Fix Concurrency Page Intro and Broken Links
  1.2/learn/by-example/kubernetes-deployment.html
  1.2/learn/deployment/aws-lambda.md
  community.md
  learn/user-guide/code-organization/coding-conventions.md
  learn/user-guide/network-communication/gRPC/implementing-grpc-services-and-clients/implementing-grpc-clients.md
  learn/user-guide/why-ballerina/cloud-native.md
  learn/user-guide/why-ballerina/concurrent.md
Labels: Area/Docs

#2533 Add Reference By Examples
  _includes/bbe-nav-swanlake.html
  home.html
  index.html
  learn-old.md
  learn.md
  learn/bbe-introduction.md
  learn/by-example/index.html
  license-of-site.md
Labels: Area/Docs

#2537 Revert the Config YML File Change
  _config.yml
Labels: Area/Docs

#2528 Add the Swan Lake Beta2 Release Note
  _data/releasenotes.yml
  downloads/swan-lake-release-notes/swan-lake-beta1/RELEASE_NOTE.md
  downloads/swan-lake-release-notes/swan-lake-beta2/RELEASE_NOTE.md
Labels: Area/Docs

#2547 Update the New Learn Column Layout
  1.0/learn/by-example/index.html
  1.1/learn/by-example/index.html
  1.2/learn/by-example/index.html
  _includes/bbe-nav-swanlake.html
  learn-beta2-column.md
  learn/bbe-introduction.md
Labels: Area/Docs

#2558 Fix Typo and Update Backticks on the TOC
  learn/user-guide/ballerina-packages/package-layout.md
  learn/user-guide/deployment/code-to-cloud/code-to-cloud-samples.md
Labels: Area/Docs
